apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: media-service
  template:
    metadata:
      labels:
        app: media-service
    spec:
      serviceAccountName: app-access
      containers:
      - name: media-service
        image: europe-west1-docker.pkg.dev/dkkom-446515/cluster-repo/media-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secret-cloud-profiler/cloud-profiler-key.json
        volumeMounts:
        - mountPath: "/var/secrets"
          name: mysecret
        - mountPath: "/var/secret-cloud-profiler"
          name: cloud-profiler-secret-vol
      volumes:
        - name: mysecret
          csi:
            driver: secrets-store-gke.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: media-secret
        - name: cloud-profiler-secret-vol
          csi:
            driver: secrets-store-gke.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: cloud-profiler-secret

---

apiVersion: v1
kind: Service
metadata:
  name: media-service
spec:
  selector:
    app: media-service
  ports:
    - protocol: TCP
      port: 8080         # Service port
      targetPort: 8080   # Container port
  type: ClusterIP
