apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: europe-west1-docker.pkg.dev/d-com-437216/cluster-repo/user-service:latest
        ports:
        - containerPort: 8080
        env:
          - name: DATABASE_IP
            valueFrom:
              secretKeyRef:
                name: database-ip
                key: DATABASE_IP
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 8080         # Service port
      targetPort: 8080   # Container port
  type: ClusterIP
