apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: message-service-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-message-service
  minReplicas: 1      # Minimum number of pods
  maxReplicas: 3      # Maximum number of pods
  metrics:
  - type: Resource
    resource:
      name: cpu        # Scale based on CPU usage
      target:
        type: Utilization
        averageUtilization: 70  # Target average CPU utilization (%)
