apiVersion: v1
kind: Service
metadata:
  name: media-service-service
spec:
  selector:
    app: {{ .Release.Name }}-media-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: {{ .Values.service.type }}
