apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-websocket-gateway
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-websocket-gateway
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-websocket-gateway
    spec:
      serviceAccountName: app-access
      containers:
      - name: websocket-gateway
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/cloud-profiler-key.json
        volumeMounts:
        - mountPath: "/var/secrets"
          name: cloud-profiler-secret-vol
        resources:                      # Add this section for HPA
          requests:
            cpu: 200m                  # Minimum guaranteed CPU (100 millicores)
            memory: 256Mi              # Minimum guaranteed memory (128 MiB)
          limits:
            cpu: 1000m                  # Maximum CPU
            memory: 512Mi              # Maximum memory
        readinessProbe:
          httpGet:
            path: /actuator/health  # Spring Actuator health check endpoint
            port: 8080
          initialDelaySeconds: 30    # Time before the first probe
          periodSeconds: 15           # Interval between probes
          successThreshold: 1        # Minimum consecutive successes
          failureThreshold: 6        # Failures before marking as Unready
        livenessProbe:
          httpGet:
            path: /actuator/health  # Liveness check on the same endpoint
            port: 8080
          initialDelaySeconds: 40    # Time before the first probe
          periodSeconds: 15          # Interval between probes
          failureThreshold: 5        # Failures before restarting the container
      volumes:
        - name: cloud-profiler-secret-vol
          csi:
            driver: secrets-store-gke.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: cloud-profiler-secret