apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api-gateway
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-api-gateway
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-api-gateway
    spec:
      serviceAccountName: app-access
      containers:
      - name: api-gateway
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        env:
          - name: GOOGLE_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: google-client-secret
                key: GOOGLE_CLIENT_SECRET
        ports:
        - containerPort: 8080
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/cloud-profiler-key.json
        volumeMounts:
        - mountPath: "/var/secrets"
          name: cloud-profiler-secret-vol
        resources:                      # Add this section for HPA
          requests:
            cpu: 100m                  # Minimum guaranteed CPU (100 millicores)
            memory: 128Mi              # Minimum guaranteed memory (128 MiB)
          limits:
            cpu: 600m                  # Maximum CPU
            memory: 500Mi              # Maximum memory
        readinessProbe:
          httpGet:
            path: /actuator/health  # Spring Actuator health check endpoint
            port: 8080
          initialDelaySeconds: 10    # Time before the first probe
          periodSeconds: 5           # Interval between probes
          successThreshold: 1        # Minimum consecutive successes
          failureThreshold: 3        # Failures before marking as Unready
        livenessProbe:
          httpGet:
            path: /actuator/health  # Liveness check on the same endpoint
            port: 8080
          initialDelaySeconds: 30    # Time before the first probe
          periodSeconds: 10          # Interval between probes
          failureThreshold: 5        # Failures before restarting the container
      volumes:
        - name: cloud-profiler-secret-vol
          csi:
            driver: secrets-store-gke.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: cloud-profiler-secret
