apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api-gateway
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-api-gateway
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-api-gateway
    spec:
      serviceAccountName: app-access
      containers:
      - name: api-gateway
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        env:
          - name: GOOGLE_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: google-client-secret
                key: GOOGLE_CLIENT_SECRET
        ports:
        - containerPort: 8080
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/cloud-profiler-key.json
        volumeMounts:
        - mountPath: "/var/secrets"
          name: cloud-profiler-secret-vol
      volumes:
        - name: cloud-profiler-secret-vol
          csi:
            driver: secrets-store-gke.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: cloud-profiler-secret
