apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-permission-service
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-permission-service
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-permission-service
    spec:
      serviceAccountName: app-access
      containers:
      - name: permission-service
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        env:
          - name: GOOGLE_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: google-client-secret
                key: GOOGLE_CLIENT_SECRET
        ports:
        - containerPort: 8080
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/cloud-profiler-key.json
        - name: DATABASE_IP
          valueFrom:
            secretKeyRef:
              name: database-replica-ip
              key: DATABASE_REPLICA_IP
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-password
              key: MYSQL_PASSWORD
        - name: REDIS_IP
          valueFrom:
            secretKeyRef:
              name: redis-ip
              key: REDIS_IP
        volumeMounts:
        - mountPath: "/var/secrets"
          name: cloud-profiler-secret-vol
        resources:                      # Add this section for HPA
          requests:
            cpu: 100m                  # Minimum guaranteed CPU (100 millicores)
            memory: 128Mi              # Minimum guaranteed memory (128 MiB)
          limits:
            cpu: 1000m                  # Maximum CPU
            memory: 1Gi              # Maximum memory
        readinessProbe:
          httpGet:
            path: /health  # Spring Actuator health check endpoint
            port: 8080
          initialDelaySeconds: 40    # Time before the first probe
          periodSeconds: 40          # Interval between probes
          timeoutSeconds:  50     # Wait up for a response
          successThreshold: 1        # Minimum consecutive successes
          failureThreshold: 10        # Failures before marking as Unready
      volumes:
        - name: cloud-profiler-secret-vol
          csi:
            driver: secrets-store-gke.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: cloud-profiler-secret
