apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-presence-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-presence-service
  template:
    metadata:
      labels:
        app: user-presence-service
    spec:
      serviceAccountName: app-access
      containers:
      - name: user-presence-service
        image: europe-west1-docker.pkg.dev/dkkom-446515/cluster-repo/user-presence-service
        ports:
        - containerPort: 8080
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /var/secrets/cloud-profiler-key.json
          - name: REDIS_IP
            valueFrom:
              secretKeyRef:
                name: redis-ip
                key: REDIS_IP
        volumeMounts:
        - mountPath: "/var/secrets"
          name: cloud-profiler-secret-vol
      volumes:
        - name: cloud-profiler-secret-vol
          csi:
            driver: secrets-store-gke.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: cloud-profiler-secret
---
apiVersion: v1
kind: Service
metadata:
  name: user-presence-service
spec:
  selector:
    app: user-presence-service
  ports:
    - protocol: TCP
      port: 8080         # Service port
      targetPort: 8080   # Container port
  type: ClusterIP
