apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-cave-service
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-cave-service
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-cave-service
    spec:
      serviceAccountName: app-access
      containers:
      - name: cave-service
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /var/secrets/cloud-profiler-key.json
          - name: DATABASE_IP
            valueFrom:
              secretKeyRef:
                name: database-ip
                key: DATABASE_IP
          - name: REDIS_IP
            valueFrom:
              secretKeyRef:
                name: redis-ip
                key: REDIS_IP
        volumeMounts:
        - mountPath: "/var/secrets"
          name: cloud-profiler-secret-vol
        resources:                      # Add this section for HPA
          requests:
            cpu: 100m                  # Minimum guaranteed CPU (100 millicores)
            memory: 128Mi              # Minimum guaranteed memory (128 MiB)
          limits:
            cpu: 900m                  # Maximum CPU
            memory: 500Mi              # Maximum memory
      volumes:
        - name: cloud-profiler-secret-vol
          csi:
            driver: secrets-store-gke.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: cloud-profiler-secret
