apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      serviceAccountName: app-access
      containers:
      - name: api-gateway
        image: europe-west1-docker.pkg.dev/dkkom-446515/cluster-repo/api-gateway:latest
        env:
          - name: GOOGLE_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: google-client-secret
                key: GOOGLE_CLIENT_SECRET
        ports:
        - containerPort: 8080  # The container listens on port 80
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/cloud-profiler-key.json
        volumeMounts:
        - mountPath: "/var/secrets"
          name: cloud-profiler-secret-vol
      volumes:
        - name: cloud-profiler-secret-vol
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: cloud-profiler-secret

---

apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
spec:
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 8080         # External port (how the service is exposed)
      targetPort: 8080     # Internal port (the port your app runs on inside the container)
  type: ClusterIP        # Use LoadBalancer or NodePort if external access is needed
