apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-user-presence-service
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-user-presence-service
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-user-presence-service
    spec:
      serviceAccountName: app-access
      containers:
      - name: user-presence-service
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /var/secrets/cloud-profiler-key.json
          - name: REDIS_IP
            valueFrom:
              secretKeyRef:
                name: redis-ip
                key: REDIS_IP
        volumeMounts:
        - mountPath: "/var/secrets"
          name: cloud-profiler-secret-vol
      volumes:
        - name: cloud-profiler-secret-vol
          csi:
            driver: secrets-store-gke.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: cloud-profiler-secret
