apiVersion: v1
kind: Service
metadata:
  name: user-presence-service
spec:
  selector:
    app: {{ .Release.Name }}-user-presence-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: {{ .Values.service.type }}
