apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-mysql-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service-mysql
  template:
    metadata:
      labels:
        app: user-service-mysql
    spec:
      containers:
      - name: user-service-mysql
        image: europe-west1-docker.pkg.dev/d-com-437216/cluster-repo/mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "admin" # Set the root password for MySQL
        - name: MYSQL_DATABASE
          value: "users_db" # Optional: Pre-create a database
        - name: MYSQL_USER
          value: "admin" # Optional: Create a new user
        - name: MYSQL_PASSWORD
          value: "admin" # Optional: Password for the new user
        ports:
        - containerPort: 3306 # MySQL default port
        volumeMounts:
        - name: user-service-mysql-data
          mountPath: /var/lib/mysql # MySQL data directory
      volumes:
      - name: user-service-mysql-data
        persistentVolumeClaim:
          claimName: user-mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: user-service-mysql
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: user-service-mysql
  type: ClusterIP
